import { createContext, useState, useEffect, useContext } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    // Navbar / Sidebar / Layout
    home: 'Home',
    findSchemes: 'Find Schemes',
    about: 'About',
    explore: 'Explore',
    dashboard: 'Dashboard',
    profile: 'Profile',
    savedSchemes: 'Saved Schemes',
    applications: 'Applications',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    citizenAssistant: 'Citizen assistance',
    navigation: 'Navigation',
    
    // Buttons & Common Actions
    search: 'Search',
    save: 'Save',
    saved: 'Saved',
    saveScheme: 'Save scheme',
    apply: 'Apply',
    applyNow: 'Apply on Official Portal',
    applying: 'Redirecting to Portal...',
    officialUrlUnavailable: 'Official application link is currently unavailable for this scheme.',
    cancel: 'Cancel',
    reset: 'Reset',
    loading: 'Loading...',
    error: 'Error',
    edit: 'Edit',
    delete: 'Delete',
    back: 'Back',
    backToSchemes: 'Back to schemes',
    viewDetails: 'View details',
    welcome: 'Welcome',
    citizen: 'Citizen',
    next: 'Next',
    notes: 'Notes',
    status: 'Status',
    
    // Dashboard Page
    welcomeUser: 'Welcome, {name}',
    citizenDashboard: 'Citizen dashboard',
    profileCompletion: 'Profile completion',
    completeText: 'complete',
    profileIncompleteNote: 'Add more details to improve future scheme matching results.',
    profileCompleteNote: 'Your profile is fully complete! Explore recommendations below.',
    helpfulNote: 'Helpful note',
    helpfulNoteContent: 'This dashboard evaluates your profile matching fit against government rules. Use the finder to explore more options.',
    recommendedSchemes: 'Recommended Schemes',
    applicationStatus: 'Your application status',
    helpfulInformation: 'Helpful Information',
    helpInfo1: 'Keep your profile details up to date for better scheme guidance.',
    helpInfo2: 'Verify official documentation before submitting applications.',
    helpInfo3: 'Use the scheme finder to narrow by category, state, age, and income.',
    loadingDashboard: 'Loading your dashboard...',
    errorDashboard: 'Failed to load dashboard summaries.',
    viewAllRecommendations: 'View all recommendations ({count})',
    viewAllSaved: 'View all saved schemes ({count})',
    viewAllApplications: 'View all applications ({count})',
    
    // Empty States
    noRecsTitle: 'No recommendations yet',
    noRecsDesc: 'Update your profile fields to generate tailored scheme matches.',
    noSavedTitle: 'No saved schemes',
    noSavedDesc: 'Bookmarked schemes will appear here once available.',
    noAppsTitle: 'No applications yet',
    noAppsDesc: 'Applied schemes and progress workflows will show up here.',
    noSavedSchemesTitle: 'No saved schemes yet',
    noSavedSchemesDesc: 'Saved and bookmarked schemes will appear here once the user has selected them from the scheme finder or dashboard.',
    noAppsTrackedTitle: 'No applications tracked yet',
    noAppsTrackedDesc: 'Browse matching schemes and apply to track progress.',
    loginToViewSaved: 'Please log in to view your saved schemes.',
    
    // Login & Register Pages
    welcomeBack: 'Welcome back',
    emailOrMobile: 'Email or mobile',
    password: 'Password',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot password?',
    newHere: 'New here?',
    createAccount: 'Create an account',
    loggingIn: 'Logging in...',
    alreadyHaveAccount: 'Already have an account?',
    registering: 'Registering...',
    confirmPassword: 'Confirm Password',
    personalDetails: 'Personal Details',
    name: 'Name',
    age: 'Age',
    gender: 'Gender',
    state: 'State',
    district: 'District',
    annualIncome: 'Annual income',
    occupation: 'Occupation',
    education: 'Education',
    category: 'Category',
    preferredLanguage: 'Preferred language',
    saveProfile: 'Save profile',
    savingProfile: 'Saving...',
    resetBtn: 'Reset',
    loadingProfile: 'Loading citizen profile...',
    profileUpdatedSuccess: 'Profile updated successfully!',
    profileLoadError: 'Failed to load profile. Please try again.',
    
    // Form Select Placeholders & Options
    selectGender: 'Select gender',
    female: 'Female',
    male: 'Male',
    other: 'Other',
    preferNotToSay: 'Prefer not to say',
    selectState: 'Select state',
    ruralUrban: 'Rural / Urban',
    selectRuralUrban: 'Select',
    rural: 'Rural',
    urban: 'Urban',
    disabilityStatus: 'Disability status',
    selectDisability: 'Select',
    yes: 'Yes',
    no: 'No',
    studentStatus: 'Student status',
    selectStudent: 'Select',
    employmentStatus: 'Employment status',
    selectEmployment: 'Select',
    employed: 'Employed',
    unemployed: 'Unemployed',
    selfEmployed: 'Self-employed',
    student: 'Student',
    selectCategory: 'Select category',
    generalCategory: 'General',
    obcCategory: 'OBC',
    scCategory: 'SC',
    stCategory: 'ST',
    
    // Scheme Finder
    schemeFinderTitle: 'Scheme finder',
    searchSchemesLabel: 'Search schemes',
    searchPlaceholder: 'Search by keyword or title',
    all: 'All',
    incomeRange: 'Income range',
    searchSchemesBtn: 'Search Schemes',
    loadingVerifiedSchemes: 'Loading verified schemes...',
    noSchemesToDisplay: 'No schemes to display yet',
    noSchemesDesc: 'Verified scheme cards will appear here once the backend and eligibility engine are connected.',
    
    // Scheme Details
    ministryPending: 'Ministry details pending',
    eligibilityCriteria: 'Who can apply?',
    benefitsDetails: 'Benefits Details',
    requiredDocuments: 'Documents you may need',
    applicationProcess: 'Application process',
    officialSource: 'Official source',
    nextSteps: 'Next steps',
    eligibilityScoreTitle: 'Eligibility Score',
    matchIndicator: 'match indicator',
    potentialBenefits: 'Potential benefits:',
    loginToViewScore: 'Log in to view your eligibility score.',
    eligibilityDetailsTitle: 'Your eligibility check',
    viewApplication: 'View application',
    schemeNotFound: 'Scheme details not found.',
    
    // Application Tracking
    applicationTrackingTitle: 'Application tracking',
    newApplication: 'New Application',
    appliedDate: 'Applied: {date}',
    lastUpdatedDate: 'Last Updated: {date}',
    editApplicationStatus: 'Edit Application Status',
    saveChanges: 'Save Changes',
    appNotesPlaceholder: 'Add application process notes, tracking numbers, or checklists...',
    deleteAppConfirm: 'Are you sure you want to delete this application record?',
    loadingApplications: 'Loading applications...',
    interested: 'Interested',
    under_review: 'Under Review',
    approved: 'Approved',
    rejected: 'Rejected',
    completed: 'Completed',
    
    // Chatbot
    chatHello: 'Hello! I am your YojanSetu Assistant. How can I help you discover and understand government schemes today?',
    chatPlaceholder: 'Ask about schemes or eligibility...',
    chatAssistantThinking: 'Assistant is thinking...',
    chatAssistantTitle: 'YojanSetu Assistant',
    chatAssistantLabel: 'AI Assistant',
    chatError: 'AI Assistant is temporarily unavailable. Please try again later.',

    // Feature 2: Why This Scheme & Eligibility Mappings
    whyThisSchemeTitle: '🎯 Why this scheme may suit you',
    whyThisSchemeBtn: 'Why this scheme?',
    infoNeededTitle: 'Information still needed:',
    docsNeededTitle: '📄 Documents You May Need',
    noDocsAvailable: 'Document requirements are not available yet.',
    explainToMeBtn: 'Explain this to me',
    disclaimerNote: 'Preliminary guidance only. Final eligibility is determined by the relevant government authority.',
    likelyMatch: 'LIKELY MATCH',
    needsMoreInfo: 'NEEDS MORE INFORMATION',
    notAMatch: 'NOT A MATCH',
    ageMatch: 'Age matches',
    incomeMatch: 'Annual income matches',
    stateMatch: 'State matches',
    genderMatch: 'Gender matches',
    categoryMatch: 'Category matches',
    occupationMatch: 'Occupation matches',
    educationMatch: 'Education matches',
    ageMissing: 'Age details',
    incomeMissing: 'Annual income details',
    stateMissing: 'State details',
    genderMissing: 'Gender details',
    categoryMissing: 'Social category details',
    occupationMissing: 'Occupation details',
    educationMissing: 'Education details',
    ageNotMatch: 'Age does not match',
    incomeNotMatch: 'Annual income exceeds limit',
    stateNotMatch: 'State does not match',
    genderNotMatch: 'Gender does not match',
    categoryNotMatch: 'Category does not match',
    occupationNotMatch: 'Occupation does not match',
    educationNotMatch: 'Education does not match',
    iNeedHelpWithTitle: 'I Need Help With',
    iNeedHelpWithSubtitle: "Tell us what you need and we'll help you find relevant government schemes.",
    whatDoYouNeedHelpWith: 'What do you need help with?',
    whatDoYouNeedPlaceholder: 'Example: I am a farmer and I need financial support...',
    findSchemesBtn: 'Find Schemes',
    recommendedForYou: 'Recommended schemes for you',
    noMatchingSchemes: "We couldn't find a matching scheme yet.",
    tryAnotherCategory: 'Try another category',
    searchAllSchemes: 'Search all schemes',
    catAgriculture: '🌾 Farming',
    catEducation: '🎓 Education',
    catHousing: '🏠 Housing',
    catEmployment: '💼 Employment',
    catWomen: '👩 Women & Child Welfare',
    catHealthcare: '🏥 Healthcare',
    catBusiness: '🏪 Small Business',
    catDisability: '♿ Disability Support',
    relevantSchemesForYou: 'Relevant Schemes For You',
    noMatchingSchemesFound: 'No matching schemes found.',
    noMatchingSchemesDesc: 'Try describing your need differently or browse all schemes.',
    findRelevantSchemesBtn: 'Find Relevant Schemes',
    speechNotSupported: 'Read Aloud is not supported by this browser.',
    speechVoiceUnavailable: 'Voice playback for this language is not available on this device.',
    readAloud: 'Read Aloud',
    stopSpeech: 'Stop',
  },
  hi: {
    // Navbar / Sidebar / Layout
    home: 'गृह',
    findSchemes: 'योजना खोजक',
    about: 'हमारे बारे में',
    explore: 'खोजें',
    dashboard: 'डैशबोर्ड',
    profile: 'प्रोफ़ाइल',
    savedSchemes: 'सहेजी गई योजनाएं',
    applications: 'आवेदन',
    login: 'लॉगिन',
    register: 'पंजीकरण',
    logout: 'लॉगआऊट',
    citizenAssistant: 'नागरिक सहायता',
    navigation: 'नेविगेशन',
    
    // Buttons & Common Actions
    search: 'खोजें',
    save: 'सहेजें',
    saved: 'सहेजा गया',
    saveScheme: 'योजना सहेजें',
    apply: 'आवेदन करें',
    applyNow: 'आधिकारिक पोर्टल पर आवेदन करें',
    applying: 'पोर्टल पर पुनर्निर्देशित किया जा रहा है...',
    officialUrlUnavailable: 'इस योजना के लिए आधिकारिक आवेदन लिंक वर्तमान में अनुपलब्ध है।',
    cancel: 'रद्द करें',
    reset: 'रीसेट करें',
    loading: 'लोड हो रहा है...',
    error: 'त्रुटि',
    edit: 'संपादित करें',
    delete: 'हटाएं',
    back: 'वापस',
    backToSchemes: 'योजनाओं पर वापस जाएं',
    viewDetails: 'विवरण देखें',
    welcome: 'स्वागत है',
    citizen: 'नागरिक',
    next: 'अगला',
    notes: 'टिप्पणी',
    status: 'स्थिति',
    
    // Dashboard Page
    welcomeUser: 'स्वागत है, {name}',
    citizenDashboard: 'नागरिक डैशबोर्ड',
    profileCompletion: 'प्रोफ़ाइल पूर्णता',
    completeText: 'पूर्ण',
    profileIncompleteNote: 'भविष्य में बेहतर योजना मिलान परिणामों के लिए और विवरण जोड़ें।',
    profileCompleteNote: 'आपकी प्रोफ़ाइल पूरी तरह से पूर्ण है! नीचे दी गई सिफारिशों का पता लगाएं।',
    helpfulNote: 'सहायक नोट',
    helpfulNoteContent: 'यह डैशबोर्ड सरकारी नियमों के खिलाफ आपकी प्रोफ़ाइल मिलान का मूल्यांकन करता है। अधिक विकल्पों का पता लगाने के लिए खोजक का उपयोग करें।',
    recommendedSchemes: 'अनुशंसित योजनाएं',
    applicationStatus: 'आपके आवेदन की स्थिति',
    helpfulInformation: 'सहायक जानकारी',
    helpInfo1: 'बेहतर योजना मार्गदर्शन के लिए अपनी प्रोफ़ाइल विवरण अपडेट रखें।',
    helpInfo2: 'आवेदन जमा करने से पहले आधिकारिक दस्तावेजों की पुष्टि करें।',
    helpInfo3: 'श्रेणी, राज्य, आयु और आय के आधार पर योजना खोजक का उपयोग करें।',
    loadingDashboard: 'डैशबोर्ड लोड किया जा रहा है...',
    errorDashboard: 'डैशबोर्ड सारांश लोड करने में विफल।',
    viewAllRecommendations: 'सभी सिफारिशें देखें ({count})',
    viewAllSaved: 'सभी सहेजी गई योजनाएं देखें ({count})',
    viewAllApplications: 'सभी आवेदन देखें ({count})',
    
    // Empty States
    noRecsTitle: 'अभी तक कोई सिफारिश नहीं',
    noRecsDesc: 'अनुकूलित योजना मिलान उत्पन्न करने के लिए अपनी प्रोफ़ाइल फ़ील्ड अपडेट करें।',
    noSavedTitle: 'कोई सहेजी गई योजना नहीं',
    noSavedDesc: 'बुकमार्क की गई योजनाएं उपलब्ध होने पर यहां दिखाई देंगी।',
    noAppsTitle: 'अभी तक कोई आवेदन नहीं',
    noAppsDesc: 'लागू की गई योजनाएं और प्रगति कार्यप्रवाह यहां दिखाई देंगे।',
    noSavedSchemesTitle: 'कोई सहेजी गई योजना नहीं',
    noSavedSchemesDesc: 'सहेजी गई और बुकमार्क की गई योजनाएं यहां दिखाई देंगी जब आप उन्हें योजना खोजक या डैशबोर्ड से चुनेंगे।',
    noAppsTrackedTitle: 'कोई आवेदन ट्रैक नहीं किया गया है',
    noAppsTrackedDesc: 'प्रगति को ट्रैक करने के लिए मिलान वाली योजनाओं को ब्राउज़ करें और आवेदन करें।',
    loginToViewSaved: 'सहेजी गई योजनाओं को देखने के लिए कृपया लॉगिन करें।',
    
    // Login & Register Pages
    welcomeBack: 'स्वागत है',
    emailOrMobile: 'ईमेल या मोबाइल',
    password: 'पासवर्ड',
    rememberMe: 'मुझे याद रखें',
    forgotPassword: 'पासवर्ड भूल गए?',
    newHere: 'यहाँ नए हैं?',
    createAccount: 'खाता बनाएं',
    loggingIn: 'लॉगिन किया जा रहा है...',
    alreadyHaveAccount: 'पहले से ही एक खाता है?',
    registering: 'पंजीकरण किया जा रहा है...',
    confirmPassword: 'पासवर्ड की पुष्टि करें',
    personalDetails: 'व्यक्तिगत विवरण',
    name: 'नाम',
    age: 'आयु',
    gender: 'लिंग',
    state: 'राज्य',
    district: 'जिला',
    annualIncome: 'वार्षिक आय',
    occupation: 'व्यवसाय',
    education: 'शिक्षा',
    category: 'श्रेणी',
    preferredLanguage: 'पसंदीदा भाषा',
    saveProfile: 'प्रोफ़ाइल सहेजें',
    savingProfile: 'सहेजा जा रहा है...',
    resetBtn: 'रीसेट',
    loadingProfile: 'नागरिक प्रोफ़ाइल लोड की जा रही है...',
    profileUpdatedSuccess: 'प्रोफ़ाइल सफलतापूर्वक अपडेट की गई!',
    profileLoadError: 'प्रोफ़ाइल लोड करने में विफल। कृपया पुन: प्रयास करें।',
    
    // Form Select Placeholders & Options
    selectGender: 'लिंग चुनें',
    female: 'महिला',
    male: 'पुरुष',
    other: 'अन्य',
    preferNotToSay: 'बताना नहीं चाहते',
    selectState: 'राज्य चुनें',
    ruralUrban: 'ग्रामीण / शहरी',
    selectRuralUrban: 'चुनें',
    rural: 'ग्रामीण',
    urban: 'शहरी',
    disabilityStatus: 'विकलांगता स्थिति',
    selectDisability: 'चुनें',
    yes: 'हाँ',
    no: 'नहीं',
    studentStatus: 'छात्र स्थिति',
    selectStudent: 'चुनें',
    employmentStatus: 'रोजगार की स्थिति',
    selectEmployment: 'चुनें',
    employed: 'नियोजित',
    unemployed: 'बेरोजगार',
    selfEmployed: 'स्व-नियोजित',
    student: 'छात्र',
    selectCategory: 'श्रेणी चुनें',
    generalCategory: 'सामान्य (General)',
    obcCategory: 'अन्य पिछड़ा वर्ग (OBC)',
    scCategory: 'अनुसूचित जाति (SC)',
    stCategory: 'अनुसूचित जनजाति (ST)',
    
    // Scheme Finder
    schemeFinderTitle: 'योजना खोजक',
    searchSchemesLabel: 'योजनाओं की खोज करें',
    searchPlaceholder: 'कीवर्ड या शीर्षक द्वारा खोजें',
    all: 'सभी',
    incomeRange: 'आय सीमा',
    searchSchemesBtn: 'योजनाएं खोजें',
    loadingVerifiedSchemes: 'सत्यापित योजनाएं लोड हो रही हैं...',
    noSchemesToDisplay: 'प्रदर्शित करने के लिए कोई योजना नहीं है',
    noSchemesDesc: 'सत्यापित योजना कार्ड यहां दिखाई देंगे जब बैकएंड और पात्रता इंजन कनेक्ट हो जाएंगे।',
    
    // Scheme Details
    ministryPending: 'मंत्रालय विवरण लंबित',
    eligibilityCriteria: 'कौन आवेदन कर सकता है?',
    benefitsDetails: 'लाभ विवरण',
    requiredDocuments: 'दस्तावेज जिनकी आपको आवश्यकता हो सकती है',
    applicationProcess: 'आवेदन प्रक्रिया',
    officialSource: 'आधिकारिक स्रोत',
    nextSteps: 'अगले कदम',
    eligibilityScoreTitle: 'पात्रता स्कोर',
    matchIndicator: 'मिलान संकेतक',
    potentialBenefits: 'संभावित लाभ:',
    loginToViewScore: 'अपना पात्रता स्कोर देखने के लिए लॉगिन करें।',
    eligibilityDetailsTitle: 'आपकी पात्रता जांच',
    viewApplication: 'आवेदन देखें',
    schemeNotFound: 'योजना विवरण नहीं मिला।',
    
    // Application Tracking
    applicationTrackingTitle: 'आवेदन ट्रैकिंग',
    newApplication: 'नया आवेदन',
    appliedDate: 'आवेदन की तिथि: {date}',
    lastUpdatedDate: 'अंतिम अपडेट: {date}',
    editApplicationStatus: 'आवेदन की स्थिति संपादित करें',
    saveChanges: 'बदलाव सहेजें',
    appNotesPlaceholder: 'आवेदन प्रक्रिया नोट, ट्रैकिंग नंबर या चेकलिस्ट जोड़ें...',
    deleteAppConfirm: 'क्या आप वाकई इस आवेदन रिकॉर्ड को हटाना चाहते हैं?',
    loadingApplications: 'आवेदन लोड हो रहे हैं...',
    interested: 'रुचि है / शुरू किया',
    under_review: 'समीक्षाधीन',
    approved: 'स्वीकृत',
    rejected: 'अस्वीकृत',
    completed: 'पूरा हो गया',
    
    // Chatbot
    chatHello: 'नमस्ते! मैं आपका भोजनसेतु एआई सहायक हूँ। आज सरकारी योजनाओं को खोजने और समझने में मैं आपकी कैसे मदद कर सकता हूँ?',
    chatPlaceholder: 'योजनाओं या पात्रता के बारे में पूछें...',
    chatAssistantThinking: 'सहायक सोच रहा है...',
    chatAssistantTitle: 'भोजनसेतु सहायक',
    chatAssistantLabel: 'एआई सहायक',
    chatError: 'एआई सहायक अस्थायी रूप से अनुपलब्ध है। कृपया बाद में पुन: प्रयास करें।',

    // Feature 2: Why This Scheme & Eligibility Mappings
    whyThisSchemeTitle: '🎯 यह योजना आपके लिए क्यों उपयुक्त हो सकती है',
    whyThisSchemeBtn: 'यह योजना क्यों?',
    infoNeededTitle: 'अभी भी आवश्यक जानकारी:',
    docsNeededTitle: '📄 दस्तावेज जिनकी आपको आवश्यकता हो सकती है',
    noDocsAvailable: 'दस्तावेजों की आवश्यकताएं अभी उपलब्ध नहीं हैं।',
    explainToMeBtn: 'मुझे यह समझाएं',
    disclaimerNote: 'केवल प्रारंभिक मार्गदर्शन। अंतिम पात्रता संबंधित सरकारी प्राधिकारी द्वारा निर्धारित की जाती है।',
    likelyMatch: 'संभावित मिलान (LIKELY MATCH)',
    needsMoreInfo: 'अधिक जानकारी की आवश्यकता है (NEEDS MORE INFORMATION)',
    notAMatch: 'मिलान नहीं है (NOT A MATCH)',
    ageMatch: 'आयु सीमा अनुकूल है',
    incomeMatch: 'वार्षिक आय सीमा के भीतर है',
    stateMatch: 'राज्य अनुकूल है',
    genderMatch: 'लिंग अनुकूल है',
    categoryMatch: 'सामाजिक श्रेणी अनुकूल है',
    occupationMatch: 'व्यवसाय अनुकूल है',
    educationMatch: 'शैक्षिक योग्यता अनुकूल है',
    ageMissing: 'आयु का विवरण',
    incomeMissing: 'वार्षिक आय का विवरण',
    stateMissing: 'राज्य का विवरण',
    genderMissing: 'लिंग का विवरण',
    categoryMissing: 'सामाजिक श्रेणी का विवरण',
    occupationMissing: 'व्यवसाय का विवरण',
    educationMissing: 'शैक्षिक योग्यता का विवरण',
    ageNotMatch: 'आयु उपयुक्त नहीं है',
    incomeNotMatch: 'वार्षिक आय सीमा से अधिक है',
    stateNotMatch: 'राज्य अनुकूल नहीं है',
    genderNotMatch: 'लिंग उपयुक्त नहीं है',
    categoryNotMatch: 'श्रेणी अनुकूल नहीं है',
    occupationNotMatch: 'व्यवसाय अनुकूल नहीं है',
    educationNotMatch: 'शैक्षिक योग्यता अनुकूल नहीं है',
    iNeedHelpWithTitle: 'मुझे किसमें मदद चाहिए?',
    iNeedHelpWithSubtitle: 'हमें बताएं कि आपको किस चीज की आवश्यकता है और हम आपको प्रासंगिक सरकारी योजनाओं को खोजने में मदद करेंगे।',
    whatDoYouNeedHelpWith: 'आपको किस चीज़ में मदद चाहिए?',
    whatDoYouNeedPlaceholder: 'उदाहरण: मैं एक किसान हूँ और मुझे वित्तीय सहायता की आवश्यकता है...',
    findSchemesBtn: 'योजनाएं खोजें',
    recommendedForYou: 'आपके लिए अनुशंसित योजनाएं',
    noMatchingSchemes: 'हमें अभी तक कोई मिलान वाली योजना नहीं मिली।',
    tryAnotherCategory: 'दूसरी श्रेणी आज़माएं',
    searchAllSchemes: 'सभी योजनाओं में खोजें',
    catAgriculture: '🌾 खेती / किसानी',
    catEducation: '🎓 शिक्षा',
    catHousing: '🏠 आवास / घर',
    catEmployment: '💼 रोजगार',
    catWomen: '👩 महिला एवं बाल कल्याण',
    catHealthcare: '🏥 स्वास्थ्य सेवा',
    catBusiness: '🏪 छोटा व्यवसाय',
    catDisability: '♿ विकलांगता सहायता',
    relevantSchemesForYou: 'आपके लिए प्रासंगिक योजनाएं',
    noMatchingSchemesFound: 'कोई मिलान वाली योजना नहीं मिली।',
    noMatchingSchemesDesc: 'अपनी आवश्यकता को अलग तरीके से बताने का प्रयास करें या सभी योजनाएं ब्राउज़ करें।',
    findRelevantSchemesBtn: 'प्रासंगिक योजनाएं खोजें',
    speechNotSupported: 'इस ब्राउज़र में जोर से पढ़ें (Read Aloud) समर्थित नहीं है।',
    speechVoiceUnavailable: 'इस डिवाइस पर इस भाषा के लिए वॉयस प्लेबैक उपलब्ध नहीं है।',
    readAloud: 'सुनें (Read Aloud)',
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    return localStorage.getItem('language') || 'en';
  });

  const setLanguage = (lang) => {
    if (translations[lang]) {
      setLanguageState(lang);
      localStorage.setItem('language', lang);
    }
  };

  const t = (key, params = {}) => {
    const dict = translations[language] || translations['en'];
    let val = dict[key] || translations['en'][key] || key;
    
    // Replace parameters like {name} or {count}
    Object.keys(params).forEach((param) => {
      val = val.replace(`{${param}}`, params[param]);
    });
    
    return val;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
