export const schemeData = [
  {
    name: 'Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)',
    shortDescription: 'Financial benefit of ₹6,000 per year in three equal installments to all landholding farmer families.',
    description: 'Pradhan Mantri Kisan Samman Nidhi (PM-KISAN) is a Central Sector scheme with 100% funding from Government of India. The scheme provides income support to all landholding farmer families having cultivable land.',
    ministry: 'Ministry of Agriculture and Farmers Welfare',
    level: 'central',
    state: null,
    category: 'agriculture',
    schemeType: 'direct_benefit_transfer',
    benefits: [
      '₹6,00,00 per year transferred directly to bank accounts',
      'Paid in three equal installments of ₹2,000 every 4 months',
      'Direct DBT payment without intermediaries',
    ],
    eligibility: 'All small and marginal landholding farmer families owning cultivable agricultural land, subject to institutional exclusions.',
    ageMin: 18,
    ageMax: 120,
    incomeLimit: null,
    eligibleGenders: ['all'],
    eligibleCategories: ['all'],
    eligibleOccupations: ['farmer'],
    eligibleEducation: ['all'],
    eligibleStates: ['all'],
    requiredDocuments: [
      'Aadhaar Card',
      'Land Ownership Record / Khasra-Khatauni',
      'Bank Account Details / Passbook',
    ],
    applicationProcess: 'Apply online at the PM-KISAN portal or through local Common Service Centers (CSC) / Village Revenue Officers.',
    applicationUrl: 'https://pmkisan.gov.in',
    officialSource: 'https://pmkisan.gov.in',
    applicationMethod: 'ONLINE',
    isActive: true,
  },
  {
    name: 'Ayushman Bharat - Pradhan Mantri Jan Arogya Yojana (PM-JAY)',
    shortDescription: 'Health cover of up to ₹5 lakh per family per year for secondary and tertiary hospitalization.',
    description: 'PM-JAY is the world\'s largest health assurance scheme providing a health cover of ₹5 lakh per family per year for secondary and tertiary care hospitalization to bottom 40% vulnerable families.',
    ministry: 'Ministry of Health and Family Welfare',
    level: 'central',
    state: null,
    category: 'healthcare',
    schemeType: 'health_insurance',
    benefits: [
      'Cashless and paperless access to healthcare services up to ₹5 lakh/year per family',
      'Covers up to 3 days of pre-hospitalization and 15 days post-hospitalization',
      'Applicable across all empanelled public and private hospitals across India',
    ],
    eligibility: 'Families identified as deprived/vulnerable as per Socio-Economic Caste Census (SECC) data and eligible low-income households.',
    ageMin: 0,
    ageMax: 120,
    incomeLimit: 250000,
    eligibleGenders: ['all'],
    eligibleCategories: ['all'],
    eligibleOccupations: ['all'],
    eligibleEducation: ['all'],
    eligibleStates: ['all'],
    requiredDocuments: [
      'Aadhaar Card',
      'Ration Card',
      'SECC Identification Document / BPL Proof',
      'Income Certificate',
    ],
    applicationProcess: 'Verify eligibility on the PM-JAY portal or visit an empanelled public/private hospital or CSC for Ayushman Card generation.',
    applicationUrl: null,
    officialSource: 'https://pmjay.gov.in',
    applicationMethod: 'INFORMATION_ONLY',
    isActive: true,
  },
  {
    name: 'Post-Matric Scholarship Scheme for SC/ST/OBC Students',
    shortDescription: 'Financial support for post-matriculation / post-secondary education for eligible underprivileged students.',
    description: 'A Centrally Sponsored Scheme that provides financial assistance to SC, ST, and OBC students studying at post-matriculation or post-secondary stages to enable them to complete their education.',
    ministry: 'Ministry of Social Justice and Empowerment',
    level: 'central',
    state: null,
    category: 'education',
    schemeType: 'scholarship',
    benefits: [
      'Coverage of non-refundable tuition and institutional fees',
      'Monthly maintenance allowance based on hosteller or day-scholar status',
      'Study tour charges, thesis typing/printing charges for research scholars',
    ],
    eligibility: 'Students belonging to SC/ST/OBC categories pursuing post-10th standard studies with family income below the prescribed threshold.',
    ageMin: 14,
    ageMax: 35,
    incomeLimit: 250000,
    eligibleGenders: ['all'],
    eligibleCategories: ['sc', 'st', 'obc'],
    eligibleOccupations: ['student'],
    eligibleEducation: ['10th_pass', '12th_pass', 'graduate', 'post_graduate'],
    eligibleStates: ['all'],
    requiredDocuments: [
      'Aadhaar Card',
      'Caste Certificate',
      'Income Certificate',
      'Previous Qualifying Marksheet',
      'Fee Receipt / College Admission Document',
      'Bank Passbook in Student\'s Name',
    ],
    applicationProcess: 'Submit application on the National Scholarship Portal (NSP) and get it verified by the respective educational institution.',
    applicationUrl: 'https://scholarships.gov.in',
    officialSource: 'https://scholarships.gov.in',
    applicationMethod: 'ONLINE',
    isActive: true,
  },
  {
    name: 'Pradhan Mantri Awas Yojana - Gramin (PMAY-G)',
    shortDescription: 'Financial grant of ₹1.20 lakh (plains) to ₹1.30 lakh (hilly areas) for constructing a pucca house.',
    description: 'PMAY-G aims to provide pucca houses with basic amenities to all houseless households and households living in kutcha and dilapidated houses in rural areas.',
    ministry: 'Ministry of Rural Development',
    level: 'central',
    state: null,
    category: 'housing',
    schemeType: 'financial_assistance',
    benefits: [
      'Unit assistance of ₹1,20,000 in plains and ₹1,30,000 in hilly/difficult areas',
      '90-95 days of unskilled labour support under MGNREGS',
      'Additional assistance of ₹12,000 for toilet construction under Swachh Bharat Mission',
    ],
    eligibility: 'Houseless families and those living in 0, 1, or 2 room kutcha houses with kutcha roof and wall as identified by SECC/Awaas+ lists.',
    ageMin: 18,
    ageMax: 120,
    incomeLimit: 300000,
    eligibleGenders: ['all'],
    eligibleCategories: ['all'],
    eligibleOccupations: ['all'],
    eligibleEducation: ['all'],
    eligibleStates: ['all'],
    requiredDocuments: [
      'Aadhaar Card',
      'Bank Account Details',
      'MGNREGA Job Card Number',
      'Land / Site Document',
      'Income Certificate',
    ],
    applicationProcess: 'Beneficiary list is finalized by Gram Sabha based on SECC/Awaas+ data. Applications can be verified through Gram Panchayat.',
    applicationUrl: null,
    officialSource: 'https://pmayg.nic.in',
    applicationMethod: 'OFFLINE',
    isActive: true,
  },
  {
    name: 'Pradhan Mantri Ujjwala Yojana (PMUY 2.0)',
    shortDescription: 'Deposit-free LPG connection along with free first refill and stove to adult women from poor households.',
    description: 'PMUY was launched to make clean cooking fuels available to rural and deprived households that were using traditional cooking fuels such as firewood, coal, and cow-dung cakes.',
    ministry: 'Ministry of Petroleum and Natural Gas',
    level: 'central',
    state: null,
    category: 'women',
    schemeType: 'subsidy',
    benefits: [
      'Deposit-free LPG connection including cylinder, regulator, and hose pipe',
      'First refill and gas stove (hotplate) provided free of cost',
      'Direct targeted subsidy on domestic LPG refills',
    ],
    eligibility: 'Adult woman (age 18+) belonging to poor / BPL household with no existing LPG connection in the family.',
    ageMin: 18,
    ageMax: 120,
    incomeLimit: 200000,
    eligibleGenders: ['female'],
    eligibleCategories: ['all'],
    eligibleOccupations: ['all'],
    eligibleEducation: ['all'],
    eligibleStates: ['all'],
    requiredDocuments: [
      'Aadhaar Card of Applicant and Family Members',
      'Ration Card / Proof of BPL status',
      'Bank Account Passbook',
      'Address Proof',
    ],
    applicationProcess: 'Apply online at PMUY portal or submit application form at nearest LPG distributor.',
    applicationUrl: 'https://www.pmuy.gov.in/ujjwala2.html',
    officialSource: 'https://pmuy.gov.in',
    applicationMethod: 'ONLINE_AND_OFFLINE',
    isActive: true,
  },
  {
    name: 'Pradhan Mantri Kaushal Vikas Yojana (PMKVY 4.0)',
    shortDescription: 'Industry-relevant, free skill training and recognized government certification for youth.',
    description: 'PMKVY is the flagship skill development scheme providing youth with industry-relevant skill training, Recognition of Prior Learning (RPL), and placement support.',
    ministry: 'Ministry of Skill Development and Entrepreneurship',
    level: 'central',
    state: null,
    category: 'skill_development',
    schemeType: 'training',
    benefits: [
      '100% free skill training in NSQF-aligned job roles',
      'Government skill certification and digital skill badge',
      'Post-training placement assistance and travel/boarding stipend',
    ],
    eligibility: 'Indian youth who are school/college dropouts, unemployed, or seeking to upskill/reskill.',
    ageMin: 15,
    ageMax: 45,
    incomeLimit: null,
    eligibleGenders: ['all'],
    eligibleCategories: ['all'],
    eligibleOccupations: ['unemployed', 'student', 'self_employed', 'all'],
    eligibleEducation: ['none', '10th_pass', '12th_pass', 'graduate', 'all'],
    eligibleStates: ['all'],
    requiredDocuments: [
      'Aadhaar Card',
      'Educational Marksheets (if applicable)',
      'Bank Account Details',
      'Passport-size Photograph',
    ],
    applicationProcess: 'Register on the Skill India Digital Hub (SIDH) portal or visit an affiliated Pradhan Mantri Kaushal Kendra (PMKK).',
    applicationUrl: 'https://www.skillindiadigital.gov.in',
    officialSource: 'https://pmkvyofficial.org',
    applicationMethod: 'ONLINE',
    isActive: true,
  },
  {
    name: 'PM Street Vendor\'s AtmaNirbhar Nidhi (PM SVANidhi)',
    shortDescription: 'Collateral-free working capital micro-loans up to ₹50,000 with 7% interest subsidy for street vendors.',
    description: 'PM SVANidhi provides working capital loans to street vendors to resume their livelihoods affected by economic disruptions, with progressive credit limits and cashback incentives on digital transactions.',
    ministry: 'Ministry of Housing and Urban Affairs',
    level: 'central',
    state: null,
    category: 'employment',
    schemeType: 'loan',
    benefits: [
      'Initial collateral-free loan of ₹10,000, progressing to ₹20,000 and ₹50,000 on timely repayment',
      '7% annual interest subsidy credited directly to bank account',
      'Cashback up to ₹1,200 per year on digital transactions',
    ],
    eligibility: 'Urban street vendors holding a Certificate of Vending / ID card issued by Urban Local Bodies (ULBs) or Recommendation Letter.',
    ageMin: 18,
    ageMax: 70,
    incomeLimit: null,
    eligibleGenders: ['all'],
    eligibleCategories: ['all'],
    eligibleOccupations: ['self_employed', 'all'],
    eligibleEducation: ['all'],
    eligibleStates: ['all'],
    requiredDocuments: [
      'Aadhaar Card',
      'Vending Certificate / Urban Local Body Letter',
      'Bank Account Details',
      'Mobile Number linked to Aadhaar',
    ],
    applicationProcess: 'Apply on the PM SVANidhi portal directly or through ULBs / CSCs / Banking Correspondents.',
    applicationUrl: 'https://pmsvanidhi.mohua.gov.in',
    officialSource: 'https://pmsvanidhi.mohua.gov.in',
    applicationMethod: 'ONLINE',
    isActive: true,
  },
  {
    name: 'Mukhyamantri Kisan Kalyan Yojana (Madhya Pradesh)',
    shortDescription: 'Additional annual financial assistance of ₹4,000 to PM-KISAN beneficiary farmers in Madhya Pradesh.',
    description: 'A state-level initiative by the Government of Madhya Pradesh to supplement the PM-KISAN scheme by providing an additional ₹4,000 per year to farmers registered under PM-KISAN.',
    ministry: 'Department of Farmers Welfare and Agriculture Development, MP',
    level: 'state',
    state: 'Madhya Pradesh',
    category: 'agriculture',
    schemeType: 'direct_benefit_transfer',
    benefits: [
      '₹4,000 per year paid in two equal installments of ₹2,000 directly to bank accounts',
      'Combines with PM-KISAN to provide total annual benefit of ₹10,000 for MP farmers',
    ],
    eligibility: 'Farmers resident in Madhya Pradesh who are active beneficiaries of the PM-KISAN scheme and own agricultural land in MP.',
    ageMin: 18,
    ageMax: 120,
    incomeLimit: null,
    eligibleGenders: ['all'],
    eligibleCategories: ['all'],
    eligibleOccupations: ['farmer'],
    eligibleEducation: ['all'],
    eligibleStates: ['Madhya Pradesh'],
    requiredDocuments: [
      'PM-KISAN Registration Number',
      'Aadhaar Card',
      'Samagra ID',
      'Land Records (Khasra/B-1)',
      'Bank Account Details',
    ],
    applicationProcess: 'Registration can be completed via SAARA portal (saara.mp.gov.in) through the local Patwari or Village Nodal Officer.',
    applicationUrl: null,
    officialSource: 'https://saara.mp.gov.in',
    applicationMethod: 'OFFLINE',
    isActive: true,
  },
  {
    name: 'Mukhyamantri Majhi Ladki Bahin Yojana (Maharashtra)',
    shortDescription: 'Monthly financial assistance of ₹1,500 directly transferred to eligible women in Maharashtra.',
    description: 'Mukhyamantri Majhi Ladki Bahin Yojana provides monthly financial independence and social security support to underprivileged women in the state of Maharashtra.',
    ministry: 'Women and Child Development Department, Maharashtra',
    level: 'state',
    state: 'Maharashtra',
    category: 'women',
    schemeType: 'financial_assistance',
    benefits: [
      'Direct cash transfer of ₹1,500 every month (₹18,000 annually) into Aadhaar-seeded bank account',
      'Direct benefit transfer via DBT mode without middle agents',
    ],
    eligibility: 'Married, widowed, divorced, deserted, and destitute women aged 21-65 years residing in Maharashtra with annual family income up to ₹2.5 lakh.',
    ageMin: 21,
    ageMax: 65,
    incomeLimit: 250000,
    eligibleGenders: ['female'],
    eligibleCategories: ['all'],
    eligibleOccupations: ['all'],
    eligibleEducation: ['all'],
    eligibleStates: ['Maharashtra'],
    requiredDocuments: [
      'Aadhaar Card',
      'Domicile Certificate / Maharashtra Ration Card',
      'Income Certificate (below ₹2.5 Lakh)',
      'Bank Account linked to Aadhaar',
      'Self-Declaration (Hamipatra)',
    ],
    applicationProcess: 'Apply through Nari Shakti Doot App or online portal or through Anganwadi workers / Setu Seva Kendras.',
    applicationUrl: 'https://ladakibahin.maharashtra.gov.in',
    officialSource: 'https://ladakibahin.maharashtra.gov.in',
    applicationMethod: 'ONLINE_AND_OFFLINE',
    isActive: true,
  },
  {
    name: 'Kanyashree Prakalpa (West Bengal)',
    shortDescription: 'Annual scholarship and one-time grant of ₹25,000 to encourage girl students in education.',
    description: 'Kanyashree Prakalpa improves the status and well-being of the girl child by incentivizing schooling of teenage girls and delaying their marriages until the age of 18.',
    ministry: 'Department of Women and Child Development and Social Welfare, West Bengal',
    level: 'state',
    state: 'West Bengal',
    category: 'education',
    schemeType: 'scholarship',
    benefits: [
      'Annual scholarship of ₹1,000 (K1) for girls aged 13-18 enrolled in class VIII to XII',
      'One-time financial grant of ₹25,000 (K2) upon turning 18 if unmarried and continuing education',
    ],
    eligibility: 'Unmarried girl students aged 13-18 studying in recognized schools/colleges in West Bengal.',
    ageMin: 13,
    ageMax: 19,
    incomeLimit: 120000,
    eligibleGenders: ['female'],
    eligibleCategories: ['all'],
    eligibleOccupations: ['student'],
    eligibleEducation: ['none', '10th_pass', '12th_pass', 'graduate'],
    eligibleStates: ['West Bengal'],
    requiredDocuments: [
      'Aadhaar Card',
      'Birth Certificate',
      'Proof of School/College Enrollment',
      'Unmarried Declaration',
      'Bank Account Passbook in Girl\'s Name',
    ],
    applicationProcess: 'Collect and submit application form (K1/K2) through the girl\'s registered school/institution, which uploads it to the Kanyashree portal.',
    applicationUrl: null,
    officialSource: 'https://www.wbkanyashree.gov.in',
    applicationMethod: 'OFFLINE',
    isActive: true,
  },
];

export const schemes = schemeData;
export default schemeData;